#!/usr/bin/env python3
"""Extend GUIDES with full fields: flow, tips, warnings, lib, ctype, code, config, analysis, use_cases."""

# Extended guide data for all 77 charts
# Each entry: flow=(prep, transform, method), tips=[], warnings=[], lib, ctype, code, config, analysis, use_cases
EXT = {
1: {
  "title":"カテゴリ別 商品販売数",
  "flow":("カテゴリ名＋数値","カテゴリごとに集計","棒グラフ"),
  "tips":["カテゴリ数は5〜10が読みやすい"],
  "warn":["カテゴリ数が多すぎると比較困難"],
  "lib":"Chart.js","ctype":"bar",
  "code":"new Chart(ctx, {\n  type: 'bar',\n  data: { labels, datasets: [{ data }] }\n});",
  "config":"borderRadius:4 で角丸、barPercentage:0.7 で棒幅調整",
  "analysis":"棒の高さを直接比較。最大/最小の差と全体的な偏りを把握。",
  "use":"カテゴリ別比較。例：「部門別売上高」「商品カテゴリ別販売数」",
  "datatable":{"headers":["カテゴリ名","販売数"],"rows":[["食品",320],["家電",185],["衣料",142]]}
},
2: {
  "title":"部門別 売上ランキング",
  "flow":("カテゴリ名＋数値","降順ソート","横棒グラフ"),
  "tips":["ラベルが長い場合は横棒が有効"],
  "warn":["ゼロ基点を守ること（途中から始めない）"],
  "lib":"Chart.js","ctype":"bar (horizontal)",
  "code":"new Chart(ctx, {\n  type: 'bar',\n  options: { indexAxis: 'y' }\n});",
  "config":"indexAxis:'y' で横棒化、barPercentage で棒幅を調整",
  "analysis":"ランキングの順位差を棒の長さで比較。上位/下位の格差を把握。",
  "use":"ランキング表示。例：「部門別売上ランキング」「商品別売上成長率」",
  "datatable":{"headers":["部門名","売上"],"rows":[["営業部",450],["マーケティング部",380],["企画部",290]]}
},
3: {
  "title":"チャネル別 四半期受注件数の内訳",
  "flow":("カテゴリ×系列×数値","系列ごとにグループ化","積み上げ棒"),
  "tips":["系列数は2〜5が見やすい"],
  "warn":["系列の並び順で印象が変わるので注意"],
  "lib":"Chart.js","ctype":"bar (stacked)",
  "code":"options: {\n  scales: {\n    x: { stacked: true },\n    y: { stacked: true }\n  }\n}",
  "config":"stacked:true を x,y 両方に設定。色は系列ごとに固定",
  "analysis":"合計値の比較と内訳の構成を同時に読む。特定系列の変動に注目。",
  "use":"内訳付き比較。例：「チャネル別の四半期受注件数」",
  "datatable":{"headers":["四半期","チャネル","受注件数"],"rows":[["Q1","直営",45],["Q1","パートナー",22],["Q2","直営",52]]}
},
4: {
  "title":"製品カテゴリ別 構成比の年次推移",
  "flow":("カテゴリ×系列×数値","各カテゴリを100%に正規化","100%積み上げ棒"),
  "tips":["構成比の変化が主題のとき使う"],
  "warn":["絶対値の情報が失われる点に注意"],
  "lib":"Chart.js","ctype":"bar (100% stacked)",
  "code":"scales: {\n  y: { stacked:true, max:100,\n    ticks:{callback:v=>v+'%'}\n  }\n}",
  "config":"max:100 + ticks callback で '%' 表記。stacked:true 必須",
  "analysis":"構成比の推移から主力セグメントの変動トレンドを読む。",
  "use":"構成比推移。例：「製品カテゴリ別構成比の年次推移」",
  "datatable":{"headers":["年度","カテゴリ","構成比"],"rows":[["2023","製品A",35],["2023","製品B",45],["2024","製品A",28]]}
},
5: {
  "title":"国内 vs 海外 カテゴリ別売上件数",
  "flow":("カテゴリ×2系列×数値","系列を横並びに配置","グループ棒"),
  "tips":["2系列の対比が最も効果的"],
  "warn":["3系列以上は見づらくなる"],
  "lib":"Chart.js","ctype":"bar (grouped)",
  "code":"datasets: [\n  { label:'国内', data:[...] },\n  { label:'海外', data:[...] }\n]",
  "config":"stacked:false（デフォルト）。categoryPercentage でグループ幅を調整",
  "analysis":"2系列の差を同一カテゴリ内で直接比較。差が開くカテゴリに注目。",
  "use":"対比分析。例：「国内vs海外の売上件数比較」",
  "datatable":{"headers":["カテゴリ名","国内売上","海外売上"],"rows":[["食品",85,42],["家電",63,38],["衣料",45,28]]}
},
6: {
  "title":"部門別 前年比成長率（増減）",
  "flow":("カテゴリ＋正負の数値","正負で色分け","発散棒グラフ"),
  "tips":["0を基準線として視覚的に強調する"],
  "warn":["正負の色は一般的な慣習（緑=正、赤=負）に合わせる"],
  "lib":"Chart.js","ctype":"bar (diverging)",
  "code":"backgroundColor: data.map(\n  v => v>=0 ? '#059669' : '#DC2626'\n)",
  "config":"indexAxis:'y'。backgroundColor を値の正負で動的に切替",
  "analysis":"正負の分布から全体的な傾向（改善/悪化）を把握。外れ値に注目。",
  "use":"増減比較。例：「部門別前年比成長率」",
  "datatable":{"headers":["部門名","前年比(%)"],"rows":[["営業部",25.3],["マーケティング部",-8.2],["企画部",12.7]]}
},
7: {
  "title":"2024→2025 部門別売上変化",
  "flow":("カテゴリ×2時点の数値","時点間をペアリング","スロープチャート"),
  "tips":["2時点の比較に特化。3時点以上は折れ線を使う"],
  "warn":["線の交差が多すぎると読みにくい（8項目以下推奨）"],
  "lib":"Chart.js","ctype":"line (2-point)",
  "code":"labels: ['2024','2025'],\ndatasets: sectors.map(s=>({\n  data: [s.v1, s.v2]\n}))",
  "config":"tension:0 で直線。pointRadius を大きめに設定",
  "analysis":"線の傾きで上昇/下降を判断。交差する線に注目して逆転を発見。",
  "use":"2時点比較。例：「2024→2025の部門別売上変化」",
  "datatable":{"headers":["部門名","2024年売上","2025年売上"],"rows":[["営業部",520,650],["マーケティング部",380,350],["企画部",280,340]]}
},
8: {
  "title":"主要KPI ミニトレンド一覧",
  "flow":("時系列の数値列","ポイント座標に変換","スパークライン（SVG）"),
  "tips":["KPIカードやテーブル内に埋め込む"],
  "warn":["軸ラベルを省略するのでコンテキストが必要"],
  "lib":"SVG","ctype":"polyline (mini)",
  "code":"<svg viewBox='0 0 120 45'>\n  <polyline points='...' />\n</svg>",
  "config":"viewBox を小さく設定。stroke-width:2 で見やすく",
  "analysis":"トレンドの方向性（上昇/横ばい/下降）を瞬時に把握。",
  "use":"インライン表示。例：「KPIカード内のトレンド表示」",
  "datatable":{"headers":["指標名","時系列値"],"rows":[["売上高",450,520,610],["件数",28,32,41]]}
},
9: {
  "title":"製品の多軸評価スコア比較",
  "flow":("複数の評価軸×スコア","軸を放射状に配置","レーダーチャート"),
  "tips":["軸数は5〜8が見やすい"],
  "warn":["軸の順番で形状が変わる。論理的な順序を維持する"],
  "lib":"Chart.js","ctype":"radar",
  "code":"new Chart(ctx, {\n  type: 'radar',\n  data: { labels:axes, datasets }\n});",
  "config":"scales.r: beginAtZero:true, max:100。fill:true で面積着色",
  "analysis":"多角形の面積と形状から総合力とバランスを評価。凹みが弱点。",
  "use":"多軸評価。例：「製品の品質/価格/機能性スコア比較」",
  "datatable":{"headers":["評価軸","製品名","スコア"],"rows":[["品質","製品A",85],["品質","製品B",72],["機能性","製品A",78]]}
},
10: {
  "title":"月別 新規顧客数の推移",
  "flow":("時系列データ","時間順にソート","折れ線グラフ"),
  "tips":["データ点が少ない場合は pointRadius を表示する"],
  "warn":["X軸の間隔が不等間隔だと誤解を招く"],
  "lib":"Chart.js","ctype":"line",
  "code":"new Chart(ctx, {\n  type: 'line',\n  data: { labels:months, datasets }\n});",
  "config":"tension:0.4 で滑らか。fill:true でエリア付きも可",
  "analysis":"トレンドの方向性・季節性・変化点を時系列で読む。",
  "use":"時系列推移。例：「月別新規顧客数の推移」",
  "datatable":{"headers":["月/四半期","新規顧客数"],"rows":[["1月",28],["2月",32],["3月",35]]}
},
11: {
  "title":"四半期 売上高と受注件数の推移（2軸）",
  "flow":("時系列×2指標（単位が異なる）","2軸に正規化","多軸折れ線"),
  "tips":["左右の軸で色を統一して混乱を防ぐ"],
  "warn":["2つの軸で因果関係があるように見える場合に注意（相関≠因果）"],
  "lib":"Chart.js","ctype":"line (dual axis)",
  "code":"scales: {\n  y:  { position:'left' },\n  y1: { position:'right',\n        grid:{display:false} }\n}",
  "config":"yAxisID:'y' と 'y1' を各 dataset に指定。右軸 grid は非表示に",
  "analysis":"2指標の連動性（正の相関/逆相関/無相関）を視覚的に確認。",
  "use":"2指標の相関観察。例：「売上高と受注件数の四半期推移」",
  "datatable":{"headers":["四半期","売上高（百万円）","受注件数"],"rows":[["Q1",120,45],["Q2",155,52],["Q3",188,61]]}
},
12: {
  "title":"月別 累計契約件数の推移",
  "flow":("時系列×離散値","階段状に変換","ステップライン"),
  "tips":["累積カウントやステータス変化に最適"],
  "warn":["連続値には不向き。段階的な変化がある場合のみ使用"],
  "lib":"Chart.js","ctype":"line (stepped)",
  "code":"datasets: [{\n  data,\n  stepped: 'before'\n}]",
  "config":"stepped:'before' or 'after'。pointRadius で各ステップを明示",
  "analysis":"変化のタイミングと大きさを段階的に確認。急変の時期に注目。",
  "use":"累積カウント。例：「月別累計契約件数の推移」",
  "datatable":{"headers":["月","累計契約数"],"rows":[["1月",3],["2月",5],["3月",8]]}
},
13: {
  "title":"累積売上高の四半期推移",
  "flow":("時系列×数値","面積計算","エリアチャート"),
  "tips":["fill の透過度は 0.2〜0.3 が見やすい"],
  "warn":["複数系列を重ねると後ろの系列が隠れる"],
  "lib":"Chart.js","ctype":"line (area)",
  "code":"datasets: [{\n  data,\n  fill: true,\n  backgroundColor: 'rgba(37,99,235,.15)'\n}]",
  "config":"fill:true + 低透明度 backgroundColor。tension で滑らかさ調整",
  "analysis":"面積のボリューム感からトレンドの強さと勢いを直感的に把握。",
  "use":"ボリューム付き推移。例：「累積売上高の四半期推移」",
  "datatable":{"headers":["四半期","累積売上高"],"rows":[["Q1",120],["Q2",275],["Q3",463]]}
},
14: {
  "title":"部門別 売上高の積み上げ推移",
  "flow":("時系列×複数系列×数値","系列を積み上げ","積み上げエリア"),
  "tips":["系列の並び順は安定したものを下に"],
  "warn":["下の系列ほど正確に読みやすく、上は歪んで見える"],
  "lib":"Chart.js","ctype":"line (stacked area)",
  "code":"datasets: series.map(s=>({\n  data: s.data,\n  fill: true\n}))\n// + y軸 stacked:true",
  "config":"y軸に stacked:true。各 dataset に fill:true。透過度 0.3 推奨",
  "analysis":"合計トレンドと各系列の寄与度を同時に把握。面積の増減に注目。",
  "use":"内訳付き推移。例：「部門別売上高の積み上げ推移」",
  "datatable":{"headers":["四半期","部門名","売上高"],"rows":[["Q1","営業部",45],["Q1","マーケティング部",35],["Q2","営業部",58]]}
},
15: {
  "title":"部門別 構成比の年次推移（エリア）",
  "flow":("時系列×複数系列×数値","100%に正規化","100%積み上げエリア"),
  "tips":["構成比の推移を面積で直感的に伝えられる"],
  "warn":["絶対値が見えなくなる。補足でKPIカードを併用すると良い"],
  "lib":"Chart.js","ctype":"line (100% stacked area)",
  "code":"// 各時点で合計100%に正規化\nscales: { y: {\n  stacked:true, max:100\n}}",
  "config":"stacked:true + max:100。ticks callback で '%' を追加",
  "analysis":"構成比の推移からシェアの拡大/縮小トレンドを読む。",
  "use":"シェア推移。例：「部門別構成比の年次推移」",
  "datatable":{"headers":["四半期","部門名","構成比(%)"],"rows":[["Q1","営業部",38],["Q1","マーケティング部",42],["Q2","営業部",42]]}
},
16: {
  "title":"イベント発生頻度 カレンダー表示",
  "flow":("日付×イベント件数","曜日×週のグリッドに変換","カレンダーヒートマップ"),
  "tips":["GitHub の Contributions グラフと同じ発想"],
  "warn":["色覚多様性を考慮し、色相ではなく明度で段階を表現する"],
  "lib":"HTML/CSS","ctype":"grid (heatmap)",
  "code":"// CSS Grid で 曜日×週\ndisplay: grid;\ngrid-template-columns:\n  repeat(weeks, 1fr);",
  "config":"値を 0〜max で正規化し rgba の alpha に変換",
  "analysis":"時間パターン（曜日効果・週次リズム）を色の濃淡で発見。",
  "use":"時間パターン分析。例：「イベント開催頻度のカレンダー表示」",
  "datatable":{"headers":["日付","イベント件数"],"rows":[["2024-01-01",2],["2024-01-02",3],["2024-01-03",1]]}
},
17: {
  "title":"主要プロジェクトの実施期間ガントチャート",
  "flow":("タスク名×開始日×終了日","期間をバーに変換","ガントチャート"),
  "tips":["期間の重複や並行タスクが一目でわかる"],
  "warn":["タスク数が多すぎると縦に長くなるのでグルーピングを検討"],
  "lib":"HTML/CSS","ctype":"bar (horizontal range)",
  "code":"// flex で各行を構成\n.bar {\n  left: calc(start%);\n  width: calc(end% - start%);\n}",
  "config":"left と width を % で設定。下部にスケール（年号）を配置",
  "analysis":"期間の重複・並行度・クリティカルパスを視覚的に確認。",
  "use":"期間管理。例：「プロジェクトの実施期間一覧」「進捗管理」",
  "datatable":{"headers":["プロジェクト名","開始時点","終了時点"],"rows":[["プロジェクトA","2020-01","2028-12"],["プロジェクトB","2022-06","2030-06"],["プロジェクトC","2023-01","2031-01"]]}
},
18: {
  "title":"プロジェクト マイルストーン タイムライン",
  "flow":("日付×イベント内容","時系列順にソート","タイムライン"),
  "tips":["マイルストーンを目立たせると効果的"],
  "warn":["イベント間の時間間隔が不均等な場合は補足説明を加える"],
  "lib":"HTML/CSS","ctype":"timeline (vertical)",
  "code":"// flex で ドット + 縦線 + コンテンツ\n.timeline-item {\n  display: flex;\n  gap: 12px;\n}",
  "config":"ドットの色でカテゴリ区別。最後のイベントに縦線なし",
  "analysis":"イベントの時系列的な文脈と因果関係を追跡。",
  "use":"イベント履歴。例：「プロジェクトマイルストーンのタイムライン」",
  "datatable":{"headers":["日付","マイルストーン","カテゴリ色"],"rows":[["2023-01-15","Phase 1","blue"],["2023-06-20","Phase 2","green"],["2024-01-10","Phase 3","purple"]]}
},
19: {
  "title":"今期 vs 前期 月別受注件数",
  "flow":("月×今期値×前期値","2系列を重ねる","期間比較チャート"),
  "tips":["今期を実線・太線、前期を破線・細線で差別化"],
  "warn":["外的要因（コロナ等）で単純比較できない場合は注記を追加"],
  "lib":"Chart.js","ctype":"line (period comparison)",
  "code":"datasets: [\n  { data:current, borderWidth:2.5 },\n  { data:prev, borderDash:[5,5],\n    borderColor:'rgba(...)' }\n]",
  "config":"今期は実線(borderWidth:2.5)、前期は borderDash:[5,5] + 薄い色",
  "analysis":"今期と前期の差の推移から成長/減速のトレンドを判断。",
  "use":"前年同期比較。例：「今期vs前期の月別受注件数」",
  "datatable":{"headers":["月","今期の値","前期の値"],"rows":[["1月",28,24],["2月",32,29],["3月",35,31]]}
},
20: {
  "title":"月別 株価・指数の変動",
  "flow":("月×始値×終値×高値×安値","OHLC変換","ローソク足"),
  "tips":["陽線（終値>始値）は緑、陰線は赤が一般的"],
  "warn":["ヒゲ（高値/安値）の表現にはカスタム描画が必要"],
  "lib":"Chart.js","ctype":"bar (OHLC)",
  "code":"// stacked bar: base(透明) + body(着色)\ndatasets: [\n  { data:bases, backgroundColor:'transparent' },\n  { data:bodies, backgroundColor:colors }\n]",
  "config":"終値≧始値→緑、終値<始値→赤で色分け。stacked:true",
  "analysis":"始値と終値の関係から各期間の価格トレンドを判断。",
  "use":"変動分析。例：「月別の株価変動（始値-終値）」",
  "datatable":{"headers":["月","始値","終値"],"rows":[["1月",100,105],["2月",105,98],["3月",98,112]]}
},
21: {
  "title":"商品価格帯 分布ヒストグラム",
  "flow":("数値列（生データ）","値の範囲をビン(区間)に分割し頻度をカウント","ヒストグラム"),
  "tips":["ビン数はスタージェスの公式(1+log2(n))を目安に"],
  "warn":["ビン幅で見え方が大きく変わるので複数パターンを試す"],
  "lib":"D3.js / Chart.js","ctype":"bar (no gap)",
  "code":"// D3でビンニング\nconst bins = d3.bin()\n  .thresholds(10)(data);",
  "config":"Chart.js: barPercentage:1, categoryPercentage:1 で隙間なし",
  "analysis":"棒の高さが頻度、分布の形状（正規・歪み・二峰性）を把握。中心傾向とばらつきを同時に読む。",
  "use":"データの分布形状とばらつきの把握。例：「商品価格帯分布」「売上のばらつき分析」",
  "datatable":{"headers":["価格帯","商品数"],"rows":[["1000-5000円",28],["5000-10000円",45],["10000-50000円",62]]}
},
22: {
  "title":"A製品 vs B製品 価格分布の比較",
  "flow":("数値列（生データ）","ビン分割→各ビン中央点を結ぶ","度数ポリゴン"),
  "tips":["2つ以上の分布を重ねて比較する場合に最適"],
  "warn":["面を塗ると重なりが見えにくい。fill:false 推奨"],
  "lib":"Chart.js","ctype":"line",
  "code":"type: 'line',\ndata: {\n  labels: binCenters,\n  datasets: [\n    { data:freq1, fill:false },\n    { data:freq2, fill:false }\n  ]\n}",
  "config":"fill:false。tension:0.3 で滑らかに。複数系列を色で区別",
  "analysis":"2つの分布の形状差から集団間の特性の違いを比較。",
  "use":"分布比較。例：「A製品 vs B製品の価格分布比較」",
  "datatable":{"headers":["価格帯","A製品数","B製品数"],"rows":[["1000-5000円",28,15],["5000-10000円",45,32],["10000-50000円",62,58]]}
},
23: {
  "title":"カテゴリ別 単価の箱ひげ図",
  "flow":("数値列（生データ）","五数要約（min/Q1/中央値/Q3/max）を計算","箱ひげ図"),
  "tips":["外れ値（1.5×IQR超）は個別の点で表示する"],
  "warn":["サンプル数が少ない場合は四分位の信頼性が低い"],
  "lib":"SVG","ctype":"box plot (custom)",
  "code":"// SVG で rect(IQR箱) + line(ひげ/中央値)\n<rect x={q1} width={q3-q1} />\n<line x1={median} x2={median} />",
  "config":"横方向のスケールで値を位置に変換。カテゴリごとに Y をずらす",
  "analysis":"中央値の位置、箱の幅（IQR）、ひげの長さから分布の特性を把握。",
  "use":"分布比較。例：「カテゴリ別単価の箱ひげ図」",
  "datatable":{"headers":["カテゴリ名","Q1/中央値/Q3/min/max"],"rows":[["カテゴリA","400/800/1200/150/3500"],["カテゴリB","300/650/1100/100/2800"],["カテゴリC","250/550/950/80/2200"]]}
},
24: {
  "title":"販売単価の密度分布（バイオリン）",
  "flow":("数値列（生データ）","カーネル密度推定（KDE）","バイオリンプロット"),
  "tips":["箱ひげ図では見えない分布の形状（二峰性等）が表現可能"],
  "warn":["バンド幅の選択で形状が大きく変わる"],
  "lib":"Chart.js","ctype":"line (area / KDE)",
  "code":"// fill:true の line で密度曲線を表現\ndatasets: [{\n  data: kde_values,\n  fill: true,\n  tension: 0.4\n}]",
  "config":"tension:0.4 で滑らか。fill:true + 透過色",
  "analysis":"分布の形状（対称/歪み/多峰性）を密度曲線の形で直感的に理解。",
  "use":"分布形状の詳細分析。例：「販売単価の密度分布」",
  "datatable":{"headers":["単価","密度"],"rows":[["5000",0.0008],["8000",0.0015],["12000",0.0012]]}
},
25: {
  "title":"カテゴリ別 個別データの分布",
  "flow":("カテゴリ×数値","X軸にジッターを加えてプロット","ストリップチャート"),
  "tips":["データ点数が多い場合は透過度を上げて重なりを表現"],
  "warn":["点が重なりすぎると密度がわからない。ジッター量を調整する"],
  "lib":"Chart.js","ctype":"scatter (jittered)",
  "code":"type: 'scatter',\ndata: points.map(p=>({\n  x: catIndex + jitter(),\n  y: p.value\n}))",
  "config":"ジッター: Math.random()*0.3-0.15。ticks callback でカテゴリ名に変換",
  "analysis":"個々のデータ点の分布から偏り・クラスタ・外れ値を発見。",
  "use":"個別データ点の分布。例：「カテゴリ別の個別データ分布」",
  "datatable":{"headers":["カテゴリID","単価"],"rows":[["カテA_001",950],["カテA_002",1350],["カテB_001",780]]}
},
26: {
  "title":"収益率の正規性検証 QQプロット",
  "flow":("数値列（生データ）","ソート→理論分位点を計算","QQプロット"),
  "tips":["点が対角線に沿えば正規分布と判断できる"],
  "warn":["サンプル数が30未満だと信頼性が低い"],
  "lib":"Chart.js","ctype":"scatter + line",
  "code":"// 対角線を破線で追加\ndatasets: [\n  { type:'scatter', data:qqPoints },\n  { type:'line', data:diagonal,\n    borderDash:[6,3] }\n]",
  "config":"逆正規分布関数でX値、ソート済みデータでY値",
  "analysis":"対角線からの乖離パターンで分布の歪み・裾の重さを診断。",
  "use":"正規性検定。例：「収益率の正規性検証」",
  "datatable":{"headers":["理論分位点","サンプル分位点"],"rows":[[-2.5,-2.3],[-0.8,-0.9],[0.5,0.6]]}
},
27: {
  "title":"売上データの累積分布関数",
  "flow":("数値列（生データ）","ソート→累積確率 i/n を計算","累積分布関数"),
  "tips":["パーセンタイル値の読み取りに便利"],
  "warn":["データのソートを忘れずに（昇順）"],
  "lib":"Chart.js","ctype":"line (CDF)",
  "code":"// ソート済みデータの累積確率\nconst cdf = sorted.map(\n  (v,i) => ({x:v, y:(i+1)/n})\n);",
  "config":"fill:true で下を塗りつぶし。Y軸 ticks で '%' 表記",
  "analysis":"任意の値以下の割合を読み取り。中央値やパーセンタイルを確認。",
  "use":"分布の累積把握。例：「売上データの累積分布」",
  "datatable":{"headers":["売上額","累積確率"],"rows":[["100",0.05],["500",0.35],["1000",0.72]]}
},
28: {
  "title":"年度別 売上分布の推移",
  "flow":("複数期間×数値列","各期間のKDE→Yオフセット","リッジラインプロット"),
  "tips":["時系列での分布変化を一覧比較するのに最適"],
  "warn":["オフセット量が大きいと重なりが少なく比較しにくい"],
  "lib":"Chart.js","ctype":"line (offset area)",
  "code":"// 各年の密度カーブにYオフセットを加算\ndatasets: years.map((y,i)=>({\n  data: kde[y].map(v=>v+i*offset),\n  fill: true\n}))",
  "config":"各年のデータにオフセットを加算。fill:true + 透過色",
  "analysis":"分布の形状変化を時系列で追跡。ピーク位置の移動に注目。",
  "use":"分布の時系列変化。例：「年度別売上分布の推移」",
  "datatable":{"headers":["価格レンジ","年度別の密度"],"rows":[["100-500万","2023: 0.35, 2024: 0.28"],["500-1000万","2023: 0.45, 2024: 0.52"]]}
},
29: {
  "title":"コスト vs 効果 4象限マッピング",
  "flow":("2軸の数値データ","象限分割の閾値を設定","散布図（4象限）"),
  "tips":["象限に意味のあるラベルを付けると解釈しやすい"],
  "warn":["外れ値にスケールが引っ張られるので注意"],
  "lib":"Chart.js","ctype":"scatter",
  "code":"type: 'scatter',\n// annotation プラグインで十字線\nplugins: { annotation: {\n  line1: { yMin:avg, yMax:avg },\n  line2: { xMin:avg, xMax:avg }\n}}",
  "config":"pointRadius で点サイズ調整。annotation で十字線",
  "analysis":"4象限のどこに点が集中するかでポートフォリオの特性を分類。",
  "use":"2軸分類。例：「コストvs効果の4象限マッピング」",
  "datatable":{"headers":["コスト","効果"],"rows":[[150,850],[450,1200],[1200,2500]]}
},
30: {
  "title":"広告費と売上の相関（回帰直線付き）",
  "flow":("2軸の数値データ","最小二乗法で回帰係数を計算","回帰直線付き散布図"),
  "tips":["R²値を表示すると回帰の当てはまりが伝わる"],
  "warn":["外れ値が回帰線を大きく歪める可能性がある"],
  "lib":"Chart.js","ctype":"scatter + line",
  "code":"datasets: [\n  { type:'scatter', data:points },\n  { type:'line',\n    data:[{x:minX,y:a*minX+b},\n          {x:maxX,y:a*maxX+b}],\n    borderDash:[6,3] }\n]",
  "config":"回帰線は始点と終点の2点で定義。borderDash で破線",
  "analysis":"相関の強さ（R²）と方向（正/負）を視覚的に確認。",
  "use":"相関分析。例：「広告費と売上の相関」",
  "datatable":{"headers":["広告費","売上"],"rows":[[200,750],[500,1150],[1000,1950]]}
},
31: {
  "title":"売上 × 成長率 × 利益 バブル分析",
  "flow":("3軸の数値データ","第3変数をバブルサイズに変換","バブルチャート"),
  "tips":["面積を値に比例させる（r = sqrt(value)）のが正確"],
  "warn":["バブルが重なりすぎると読みにくい。透過度を調整する"],
  "lib":"Chart.js","ctype":"bubble",
  "code":"type: 'bubble',\ndata: points.map(p=>({\n  x: p.valuation,\n  y: p.growth,\n  r: Math.sqrt(p.funding)*scale\n}))",
  "config":"r は sqrt 変換で面積比例に。透過色で重なりを表現",
  "analysis":"3変数の関係を2D上で同時に把握。大きなバブルの位置に注目。",
  "use":"3次元関係。例：「売上×成長率×利益のバブル分析」",
  "datatable":{"headers":["売上","成長率","利益"],"rows":[[800,15,50],[1200,22,85],[1800,18,120]]}
},
32: {
  "title":"指標間の相関マトリックス",
  "flow":("多変量データ","相関係数行列を計算","相関マトリックス"),
  "tips":["対角線は常に1.00。上三角か下三角のみ表示しても良い"],
  "warn":["相関は因果関係を意味しない。解釈に注意"],
  "lib":"HTML/CSS","ctype":"grid (correlation)",
  "code":"// CSS Grid で N×N マトリックス\n// 相関係数 -1〜1 を色に変換\nconst color = corr >= 0\n  ? `rgba(37,99,235,${corr})`\n  : `rgba(220,38,38,${-corr})`;",
  "config":"正の相関は青系、負の相関は赤系で色分け",
  "analysis":"強い相関のペアを発見し、多変量間の構造を把握。",
  "use":"変数間関係の全体像。例：「財務指標間の相関マトリックス」",
  "datatable":{"headers":["変数名","相関係数"],"rows":[["売上-広告費",0.78],["売上-顧客数",0.85],["広告費-利益",0.62]]}
},
33: {
  "title":"カテゴリ × 地域 売上件数ヒートマップ",
  "flow":("2軸のクロス集計値","値を色濃度に変換","ヒートマップ"),
  "tips":["セル内に数値を表示すると正確な読み取りが可能"],
  "warn":["色覚多様性に配慮し、青-白系が安全"],
  "lib":"HTML/CSS","ctype":"grid (heatmap)",
  "code":"// CSS Grid で行×列\n// 最大値で正規化\nconst alpha = val / maxVal;\ncell.style.background =\n  `rgba(37,99,235,${alpha})`;",
  "config":"最大値で正規化し rgba の alpha に変換。セル内に数値表示",
  "analysis":"色の濃いセルに集中度が高い。パターンや空白地帯に注目。",
  "use":"クロス集計の可視化。例：「カテゴリ×地域の売上件数ヒートマップ」",
  "datatable":{"headers":["カテゴリ名","地域名","売上件数"],"rows":[["食品","下期",28],["食品","上期",45],["家電","下期",22]]}
},
34: {
  "title":"取引先⇔製品 ネットワーク図",
  "flow":("ノード一覧＋接続関係","力学モデルでレイアウト","ネットワーク図"),
  "tips":["ノードサイズで重要度（次数）を表現すると読みやすい"],
  "warn":["ノード数が多すぎると見通しが悪くなる。フィルタリングを検討"],
  "lib":"SVG","ctype":"network (force-directed)",
  "code":"// SVG で circle(ノード) + line(エッジ)\n<circle cx={x} cy={y} r={size} />\n<line x1={x1} y1={y1}\n      x2={x2} y2={y2} />",
  "config":"ノードサイズで重要度、色でカテゴリを区別",
  "analysis":"ハブ（多接続ノード）とクラスタの構造を発見。",
  "use":"関係性の可視化。例：「取引先⇔製品のネットワーク」",
  "datatable":{"headers":["取引先","製品","関係"],"rows":[["Fund A","CompanyX","connected"],["Fund A","CompanyY","connected"],["Fund B","CompanyX","connected"]]}
},
35: {
  "title":"チャネル→製品カテゴリへの売上フロー",
  "flow":("ソース×ターゲット×フロー量","フロー帯の太さに変換","サンキーダイアグラム"),
  "tips":["ノードを左右に分けてフローの方向を明確にする"],
  "warn":["フローが多すぎると帯が重なって読みにくい"],
  "lib":"SVG","ctype":"sankey (custom)",
  "code":"// SVG path でベジェ曲線フロー\n<path d={`M${x1},${y1}\n  C${cx1},${y1} ${cx2},${y2}\n  ${x2},${y2}`}\n  stroke-width={flow} />",
  "config":"stroke-width でフロー量表現。opacity:0.4 で重なりを可視化",
  "analysis":"フローの太さから主要な経路と量的な分布を把握。",
  "use":"フロー可視化。例：「チャネル→製品カテゴリへの売上フロー」",
  "datatable":{"headers":["チャネル","製品カテゴリ","売上"],"rows":[["VC","下期",120],["CVC","下期",85],["VC","上期",150]]}
},
36: {
  "title":"部門間 連携関係",
  "flow":("グループ間の相互関係量","円弧とコードに変換","コードダイアグラム"),
  "tips":["対称な関係の可視化に最適"],
  "warn":["グループ数が多すぎるとコードが密集して見にくい"],
  "lib":"SVG","ctype":"chord (circular)",
  "code":"// SVG で円弧 + ベジェ曲線コード\n// 三角関数で座標計算\nconst x = cx + r*Math.cos(angle);\nconst y = cy + r*Math.sin(angle);",
  "config":"opacity を低めに設定し重なりを表現",
  "analysis":"太いコードが強い関係。円弧の長さがグループの総量を示す。",
  "use":"相互関係。例：「部門間の連携関係」",
  "datatable":{"headers":["カテゴリ名","共同投資件数"],"rows":[["食品",48],["家電",35],["日用品",22]]}
},
37: {
  "title":"業務プロセス フローチャート",
  "flow":("工程名＋接続関係","ノードと矢印を配置","フローチャート"),
  "tips":["上→下 or 左→右の一方向で統一する"],
  "warn":["分岐やループがある場合は別途注記を追加"],
  "lib":"SVG","ctype":"flowchart (directed)",
  "code":"// SVG で rect + line + marker(矢印)\n<marker id='arrow'>\n  <path d='M0,0 L10,5 L0,10 Z'/>\n</marker>\n<line marker-end='url(#arrow)'/>",
  "config":"marker-end で矢印ヘッド。色でカテゴリ区別",
  "analysis":"プロセスの全体像と各工程の接続関係を把握。",
  "use":"プロセス可視化。例：「データパイプラインのフロー」",
  "datatable":{"headers":["工程名","接続関係"],"rows":[["データ収集","→"],["正規化","→"],["分析","→"],["公開","END"]]}
},
38: {
  "title":"部門別 予算配分ツリーマップ",
  "flow":("カテゴリ×数値","面積比に変換→グリッド配置","ツリーマップ"),
  "tips":["アスペクト比が1に近いセルほど読みやすい"],
  "warn":["小さすぎるセルはラベルが見えないので集約を検討"],
  "lib":"HTML/CSS","ctype":"treemap (grid)",
  "code":"// CSS Grid で構成\n// 大きい項目は grid-column:span 2\n.cell {\n  grid-column: span N;\n}",
  "config":"セルの面積比が値に比例するよう配置。hover で強調",
  "analysis":"大きなセルが支配的な項目。面積比から構成を直感的に把握。",
  "use":"面積比較。例：「部門別予算配分のツリーマップ」",
  "datatable":{"headers":["部門名","予算"],"rows":[["Fund Alpha",580],["Fund Beta",420],["Fund Gamma",280]]}
},
39: {
  "title":"大分類→小分類 売上構成",
  "flow":("階層データ（親子関係＋値）","角度を階層ごとに分割","サンバースト"),
  "tips":["内輪から外輪へ読み進める（親→子の関係）"],
  "warn":["階層が深すぎると外輪が細くなって読みにくい"],
  "lib":"Chart.js","ctype":"doughnut (multi-ring)",
  "code":"type: 'doughnut',\ndata: {\n  datasets: [\n    { data:inner, labels:parents },\n    { data:outer, labels:children }\n  ]\n}",
  "config":"cutout:'30%'。内輪/外輪の角度を合わせて配置",
  "analysis":"階層構造を放射状に把握。各レベルの構成比を同時に読む。",
  "use":"階層構成。例：「大分類→小分類の売上構成」",
  "datatable":{"headers":["親カテゴリ","子カテゴリ","値"],"rows":[["食品","菓子",280],["食品","調味料",200],["家電","冷凍",150]]}
},
40: {
  "title":"カテゴリ間 類似度デンドログラム",
  "flow":("距離/類似度行列","階層的クラスタリング","デンドログラム"),
  "tips":["結合の高さ（距離）でクラスタの切り分けポイントを判断"],
  "warn":["距離指標（ユークリッド/コサイン等）の選択が結果に影響"],
  "lib":"SVG","ctype":"dendrogram (tree)",
  "code":"// SVG で垂直線 + 水平線\n<line x1={x} y1={y_leaf}\n      x2={x} y2={y_merge} />\n<line x1={x_left} y1={y_merge}\n      x2={x_right} y2={y_merge} />",
  "config":"結合の高さが距離に比例するよう Y 座標を設定",
  "analysis":"結合の高さからクラスタ間の距離を比較。大きなジャンプがカットポイント。",
  "use":"クラスタ分析。例：「カテゴリ間の類似度階層」",
  "datatable":{"headers":["カテゴリ名","距離/類似度"],"rows":[["カテA",0.0],["家電",2.5],["日用品",3.8]]}
},
41: {
  "title":"カテゴリ別 件数（バブル）",
  "flow":("カテゴリ×数値","円のサイズに変換→パッキング","パックドバブル"),
  "tips":["バブルの面積比を正確にするため r=sqrt(value) を使う"],
  "warn":["バブル同士の重なりが起きないよう座標調整が必要"],
  "lib":"SVG","ctype":"packed circles",
  "code":"// SVG circle を配置\n// r = sqrt(value) でスケーリング\n<circle cx={x} cy={y}\n  r={Math.sqrt(val)*scale} />",
  "config":"面積比例に r=sqrt(value)。透過色 + stroke で境界表現",
  "analysis":"バブルのサイズ比較から主要項目と全体分布を把握。",
  "use":"面積で量を比較。例：「カテゴリ別件数」",
  "datatable":{"headers":["カテゴリ名","件数"],"rows":[["食品",148],["家電",102],["衣料",78]]}
},
42: {
  "title":"商品カテゴリ 階層分割",
  "flow":("階層データ（親子関係＋値）","各レベルを矩形で分割","アイシクルチャート"),
  "tips":["ツリーマップの縦版として階層が明確に見える"],
  "warn":["横幅が狭い項目はラベルが入らない"],
  "lib":"SVG","ctype":"icicle (partition)",
  "code":"// SVG で各レベルを横帯として描画\n// 子は親の幅を按分\n<rect x={parentX + offset}\n  width={parentW * ratio}\n  y={level * height} />",
  "config":"レベルごとに色のトーンを変える。幅が値に比例",
  "analysis":"階層の深さと各レベルの構成を縦方向に追跡。",
  "use":"階層分割。例：「投資カテゴリの階層構成」",
  "datatable":{"headers":["カテゴリ階層","値"],"rows":[["投資"],["投資/VC",450],["投資/VC/Technology",280]]}
},
43: {
  "title":"商品カテゴリ 分類ツリー",
  "flow":("ノード＋親子関係","階層レイアウト計算","ツリー図"),
  "tips":["組織図やカテゴリ分類の表現に最適"],
  "warn":["子ノードが多いレベルは横幅の確保が必要"],
  "lib":"SVG","ctype":"tree (hierarchical)",
  "code":"// SVG で circle/rect + line\n<circle cx={x} cy={y} r={8} />\n<line x1={parentX} y1={parentY}\n      x2={childX} y2={childY} />",
  "config":"レベルごとに色を変えてノードサイズを小さくする",
  "analysis":"親子関係の構造と各レベルの広がりを把握。",
  "use":"階層構造。例：「投資カテゴリの分類ツリー」",
  "datatable":{"headers":["ノード名","親子関係"],"rows":[["投資","root"],["VC","投資"],["Corporate","投資"]]}
},
44: {
  "title":"チャネル別 構成比ドーナツ",
  "flow":("カテゴリ×数値","角度に変換","ドーナツチャート"),
  "tips":["中央スペースにKPI値を配置できる"],
  "warn":["セグメント数は6以下が読みやすい。それ以上は「その他」にまとめる"],
  "lib":"Chart.js","ctype":"doughnut",
  "code":"new Chart(ctx, {\n  type: 'doughnut',\n  data: { labels, datasets:[{\n    data, cutout:'60%'\n  }]}\n});",
  "config":"cutout:'60%' で中央を空ける。hoverOffset で浮き出し",
  "analysis":"各セグメントの構成比を角度と色で比較。支配的セグメントに注目。",
  "use":"構成比表示。例：「チャネル別の構成比」",
  "datatable":{"headers":["チャネル名","構成比"],"rows":[["直販",45],["代理店",28],["EC",18]]}
},
45: {
  "title":"部門別 売上構成 円グラフ",
  "flow":("カテゴリ×数値","角度に変換","円グラフ"),
  "tips":["最大セグメントを12時方向から開始すると読みやすい"],
  "warn":["3D円グラフは歪むので使わない"],
  "lib":"Chart.js","ctype":"pie",
  "code":"new Chart(ctx, {\n  type: 'pie',\n  data: { labels, datasets:[{\n    data,\n    borderWidth:2,\n    borderColor:'#FFF'\n  }]}\n});",
  "config":"borderWidth:2 で境界を明確に。凡例を右側に配置",
  "analysis":"全体に対する各部分の割合を扇形で直感的に把握。",
  "use":"構成比一覧。例：「部門別売上構成」",
  "datatable":{"headers":["カテゴリ名","件数"],"rows":[["食品",148],["家電",102],["衣料",78]]}
},
46: {
  "title":"商品別 売上件数パレート分析",
  "flow":("カテゴリ×数値","降順ソート→累積%を計算","パレート図"),
  "tips":["80%ラインを水平に引くとパレート原則の検証ができる"],
  "warn":["棒と折れ線で軸が異なるので、読み方の説明を添える"],
  "lib":"Chart.js","ctype":"bar + line (dual axis)",
  "code":"datasets: [\n  { type:'bar', data:sorted,\n    yAxisID:'y' },\n  { type:'line', data:cumPct,\n    yAxisID:'y1' }\n]",
  "config":"右Y軸に 0-100% のスケール。yAxisID で分離",
  "analysis":"上位少数で全体の何%を占めるか（80-20法則）を検証。",
  "use":"重点分析。例：「カテゴリ別件数のパレート分析」",
  "datatable":{"headers":["カテゴリ名","件数","累積%"],"rows":[["食品",148,42],["家電",102,71],["日用品",78,93]]}
},
47: {
  "title":"四半期 売上増減ウォーターフォール",
  "flow":("項目×増加額×減少額","積み上げベース計算","ウォーターフォール"),
  "tips":["開始値と最終値を特別な色（青等）で強調する"],
  "warn":["ベース（透明棒）の計算が重要。間違えると棒の位置がずれる"],
  "lib":"Chart.js","ctype":"bar (stacked, transparent base)",
  "code":"datasets: [\n  { data:bases, backgroundColor:\n    'transparent' },\n  { data:increases, backgroundColor:\n    '#059669' },\n  { data:decreases, backgroundColor:\n    '#DC2626' }\n]",
  "config":"stacked:true。ベースは transparent。増加=緑、減少=赤",
  "analysis":"各要因の寄与度（正/負）と最終値への推移を段階的に追跡。",
  "use":"変動要因分析。例：「四半期売上の増減ウォーターフォール」",
  "datatable":{"headers":["期間/項目","増加額","減少額"],"rows":[["開始",120,0],["食品仕入",45,0],["縮小",0,-15]]}
},
48: {
  "title":"カテゴリ × 地域 市場規模マリメッコ",
  "flow":("カテゴリ×市場サイズ×構成比","幅と高さの2軸で表現","マリメッコチャート"),
  "tips":["幅＝市場サイズ、高さ＝構成比で2次元の情報を同時表示"],
  "warn":["正確な面積比較は直感的でない。数値ラベルを併記する"],
  "lib":"HTML/CSS","ctype":"marimekko (variable width)",
  "code":"// CSS flex で列を横に配置\n.column {\n  flex: 0 0 calc(marketSize%);\n}\n// 各列内を flex-direction:column",
  "config":"width を市場サイズに比例。高さをチャネル構成比に比例",
  "analysis":"面積で市場規模×構成比を同時に読む。大きいセルが主要市場。",
  "use":"市場構成の2次元分析。例：「カテゴリ×ステージの市場規模」",
  "datatable":{"headers":["カテゴリ名","市場サイズ","チャネル構成比"],"rows":[["食品",450,"下期:35%"],["家電",320,"上期:45%"]]}
},
49: {
  "title":"カテゴリ別 件数ロリポップ",
  "flow":("カテゴリ×数値","細い棒＋先端ドット","ロリポップチャート"),
  "tips":["棒グラフよりスタイリッシュで見やすい"],
  "warn":["ドットが小さすぎると値が読みにくい"],
  "lib":"Chart.js","ctype":"bar (thin + dot)",
  "code":"indexAxis: 'y',\nbarPercentage: 0.15,\nborderRadius: 20",
  "config":"indexAxis:'y' + barPercentage:0.15 で細い棒。borderRadius:20",
  "analysis":"棒グラフと同じ読み方。モダンなデザインで視覚的差別化。",
  "use":"ランキング（代替表現）。例：「カテゴリ別件数」",
  "datatable":{"headers":["カテゴリ名","件数"],"rows":[["食品",148],["家電",102],["衣料",78]]}
},
50: {
  "title":"営業プロセス ファネル分析",
  "flow":("ステージ名×件数×変換率","段階的に幅を縮小","ファネルチャート"),
  "tips":["各段階の変換率をラベルで明示する"],
  "warn":["段階間の数値差が極端だと下段が見えにくくなる"],
  "lib":"HTML/CSS","ctype":"funnel (horizontal bars)",
  "code":"// 各ステージを div として配置\n.stage {\n  width: calc(value / maxValue * 100%);\n  margin: 0 auto;\n}",
  "config":"上→下で幅を狭めて漏斗型に。各段階にテキストラベル",
  "analysis":"各段階の離脱率と全体の変換効率を段階的に把握。",
  "use":"コンバージョン分析。例：「投資プロセスのファネル」",
  "datatable":{"headers":["ステージ名","件数","変換率"],"rows":[["問い合わせ",500,"100%"],["初回面談",320,"64%"],["投資実行",185,"37%"]]}
},
51: {
  "title":"都道府県別 売上件数コロプレスマップ",
  "flow":("地域名×数値","値を色濃度に変換→地図に配置","コロプレスマップ"),
  "tips":["本格実装は D3.js + GeoJSON を使用する"],
  "warn":["面積の大きい地域が目立ちすぎる（人口密度とは無関係）"],
  "lib":"SVG","ctype":"choropleth (simplified)",
  "code":"// SVG で地域ごとに rect を配置\n// 値→色変換\nconst alpha = val / maxVal;\nrect.fill = `rgba(37,99,235,${alpha})`;",
  "config":"値を最大値で正規化し rgba の alpha に変換",
  "analysis":"色の濃い地域に投資が集中。地理的パターンを発見。",
  "use":"地域別データ。例：「都道府県別投資件数マップ」",
  "datatable":{"headers":["地域名","投資件数"],"rows":[["東京",285],["大阪",92],["福岡",48]]}
},
52: {
  "title":"主要都市別 売上額バブルマップ",
  "flow":("地域×座標×数値","座標にバブルを配置","バブルマップ"),
  "tips":["バブルの面積を値に比例させる（r=sqrt）"],
  "warn":["バブルが重なる場合は透過度を調整する"],
  "lib":"SVG","ctype":"bubble map",
  "code":"// SVG で背景地図 + circle\n<circle cx={lon} cy={lat}\n  r={Math.sqrt(val)*scale}\n  opacity='0.7' />",
  "config":"半径を売上額に比例（sqrt）。ラベルとして都市名・金額を表示",
  "analysis":"バブルのサイズと位置から地理的な投資集中度を把握。",
  "use":"地域×量の可視化。例：「都市別売上額のバブルマップ」",
  "datatable":{"headers":["都市名","売上額"],"rows":[["東京",580],["大阪",180],["福岡",95]]}
},
53: {
  "title":"店舗・拠点 ドットマップ",
  "flow":("拠点座標×カテゴリ","座標に小ドットを配置","ドットマップ"),
  "tips":["1ドット＝N件のようにスケールを明示する"],
  "warn":["密集エリアではドットが重なるのでズーム機能を検討"],
  "lib":"SVG","ctype":"dot map",
  "code":"// SVG で小さな circle を多数配置\n<circle cx={x} cy={y} r={3}\n  fill={sectorColor} />",
  "config":"色でカテゴリ区別。r:3〜5 の小さなドット",
  "analysis":"ドットの密度パターンからクラスタと空白地帯を発見。",
  "use":"分布パターン。例：「店舗・拠点の地理分布」",
  "datatable":{"headers":["位置座標","カテゴリ"],"rows":[["35.67,139.65","食品"],["34.69,135.50","家電"],["33.59,130.40","日用品"]]}
},
54: {
  "title":"地域間 取引フローマップ",
  "flow":("拠点間×フロー量","拠点間を矢印で接続","フローマップ"),
  "tips":["矢印の太さでフロー量を表現する"],
  "warn":["一方向のフローが多いと矢印が密集する"],
  "lib":"SVG","ctype":"flow map (arrows)",
  "code":"// SVG で circle(拠点) + line(フロー)\n<line x1={from.x} y1={from.y}\n  x2={to.x} y2={to.y}\n  stroke-width={flow} />",
  "config":"stroke-width でフロー量。方向性を矢印（marker-end）で示す",
  "analysis":"主要フローの方向と量的な偏りを地理的に把握。",
  "use":"クロスボーダー分析。例：「地域間の投資フロー」",
  "datatable":{"headers":["拠点名","投資フロー量"],"rows":[["Tokyo→Osaka",85],["Tokyo→Singapore",52],["Osaka→Tokyo",28]]}
},
55: {
  "title":"部門別 売上ランキング推移",
  "flow":("カテゴリ×時点×順位","順位を逆Y軸でプロット","バンプチャート"),
  "tips":["線の交差が順位変動を示す。色で個体を追跡する"],
  "warn":["カテゴリ数が多いと線が密集する（8以下推奨）"],
  "lib":"Chart.js","ctype":"line (rank, reversed Y)",
  "code":"scales: {\n  y: { reverse: true,\n    min:1, max:N }\n}\n// 各カテゴリを line dataset に",
  "config":"Y軸に reverse:true（1位が上）。tension:0.3 で滑らか",
  "analysis":"順位の変動パターン（安定/上昇/下降/逆転）を線で追跡。",
  "use":"順位変動。例：「部門別売上ランキング推移」",
  "datatable":{"headers":["カテゴリ名","四半期","順位"],"rows":[["食品","Q1",1],["食品","Q2",1],["家電","Q1",2]]}
},
56: {
  "title":"トップ5部門 ランク変動",
  "flow":("カテゴリ×時点×順位","順位を逆Y軸でプロット","ランクチャート"),
  "tips":["少数グループの推移をシンプルに表示"],
  "warn":["同順位の扱い方（平均順位/最小順位）を統一する"],
  "lib":"Chart.js","ctype":"line (rank, simple)",
  "code":"scales: {\n  y: { reverse: true,\n    ticks:{ callback:v=>v+'位' }\n  }\n}",
  "config":"reverse:true。ticks callback で '位' を付加。pointRadius 大きめ",
  "analysis":"少数グループの順位推移を時系列で追跡。",
  "use":"順位推移（シンプル版）。例：「カテゴリのランク変動」",
  "datatable":{"headers":["カテゴリ名","年度","順位"],"rows":[["食品","2023",1],["食品","2024",1],["家電","2023",2]]}
},
57: {
  "title":"製品の多軸スコア 平行座標プロット",
  "flow":("多変量データ（N軸×M個体）","各軸を平行に配置","平行座標プロット"),
  "tips":["軸の順序を工夫するとクラスタが見えやすくなる"],
  "warn":["スケールが異なる軸は正規化が必要"],
  "lib":"Chart.js","ctype":"line (parallel axes)",
  "code":"type: 'line',\nlabels: axisNames,\ndatasets: entities.map(e=>({\n  data: e.scores,\n  tension: 0\n}))",
  "config":"tension:0 で直線。X軸のグリッドで各軸を表示",
  "analysis":"線の形状パターンからプロファイルの類似性/相違性を比較。",
  "use":"多変量プロファイル比較。例：「企業の多軸スコア比較」",
  "datatable":{"headers":["評価軸","製品名","スコア"],"rows":[["品質","製品A",85],["品質","製品B",72],["機能性","製品A",78]]}
},
58: {
  "title":"部門別 前年→今年の変化（ダンベル）",
  "flow":("カテゴリ×旧値×新値","2点を線で接続","ダンベルチャート"),
  "tips":["変化の方向と大きさを同時に表現できる"],
  "warn":["旧値と新値の色を凡例で明確に示す"],
  "lib":"SVG","ctype":"dumbbell (dot-line-dot)",
  "code":"// SVG で 2点 + 接続線\n<circle cx={oldX} cy={y} r={6}\n  fill='#94A3B8' />\n<line x1={oldX} y1={y}\n  x2={newX} y2={y} />\n<circle cx={newX} cy={y} r={6}\n  fill='#2563EB' />",
  "config":"旧値（灰色）と新値（青）で色を変える。凡例で時点を説明",
  "analysis":"変化の方向（左→右 or 右→左）と量を同時に把握。",
  "use":"変化量の比較。例：「カテゴリ別の前年→今年の変化」",
  "datatable":{"headers":["カテゴリ名","旧値","新値"],"rows":[["食品",520,650],["家電",380,350],["日用品",280,340]]}
},
59: {
  "title":"KPI別 目標達成度ブレットチャート",
  "flow":("指標名×実績値×目標値","実績と目標を重ね棒で表示","ブレットチャート"),
  "tips":["複数KPIの達成度を一覧比較するのに最適"],
  "warn":["棒の太さで実績/目標を区別するので凡例を明示する"],
  "lib":"Chart.js","ctype":"bar (layered)",
  "code":"datasets: [\n  { label:'目標', data:targets,\n    barPercentage:0.9,\n    backgroundColor:'#E5E9F0' },\n  { label:'実績', data:actuals,\n    barPercentage:0.5,\n    backgroundColor:'#2563EB' }\n]",
  "config":"実績を細く(0.5)、目標を太く(0.9)。indexAxis:'y'",
  "analysis":"実績が目標を超えているか、不足しているかを視覚的に判断。",
  "use":"目標達成度。例：「KPI別の達成状況一覧」",
  "datatable":{"headers":["指標名","実績値(%)","目標値(%)"],"rows":[["売上高",85,100],["顧客数",92,100],["利益率",78,100]]}
},
60: {
  "title":"主要KPIカード：売上高・顧客数・利益率・受注数",
  "flow":("指標名×現在値×変化率","カードUIに配置","KPIカード"),
  "tips":["最も重要な3〜5指標に絞る"],
  "warn":["数値のフォーマット（通貨・%・単位）を統一する"],
  "lib":"HTML/CSS","ctype":"card (KPI)",
  "code":"// CSS Grid で横並びカード\n.kpi-grid {\n  display: grid;\n  grid-template-columns:\n    repeat(4, 1fr);\n}",
  "config":"数値は大きめモノスペース。変化率は正→緑、負→赤",
  "analysis":"主要KPIの現在値と変化方向を一目で把握。",
  "use":"ダッシュボード上段。例：「売上高・顧客数・利益率・受注数」",
  "datatable":{"headers":["指標名","現在値","変化率"],"rows":[["売上高","2,450万","+12%"],["顧客数","1,850件","+18%"],["平均単価","850円","+8%"]]}
},
61: {
  "title":"企画・開発・リリース準備の進捗",
  "flow":("工程名×完了率(%)","バーの長さに変換","進捗バー"),
  "tips":["色で状態を分ける（完了=緑、進行中=青、遅延=赤）"],
  "warn":["完了率が正確でないと誤解を招く"],
  "lib":"HTML/CSS","ctype":"progress bar",
  "code":"// 外枠 + 内枠\n<div class='track'>\n  <div class='fill'\n    style='width:${pct}%'>\n  </div>\n</div>",
  "config":"width を完了率 % で設定。数値ラベルを右端に配置",
  "analysis":"各工程の進捗状況を棒の長さで直感的に比較。",
  "use":"進捗管理。例：「データ収集・正規化・公開準備の進捗」",
  "datatable":{"headers":["工程名","完了率(%)"],"rows":[["データ収集",95],["正規化",72],["公開準備",48]]}
},
62: {
  "title":"品質スコア ゲージ表示",
  "flow":("指標名×達成率(%)","角度に変換→円弧描画","ゲージチャート"),
  "tips":["3色ゾーン（赤/橙/緑）で健全性を表現"],
  "warn":["半円表示なので 0-100% の範囲を正確にマッピングする"],
  "lib":"SVG","ctype":"gauge (arc)",
  "code":"// SVG で半円 arc path\nconst angle = (value/100) * Math.PI;\nconst x = cx + r*Math.cos(Math.PI-angle);\nconst y = cy - r*Math.sin(Math.PI-angle);",
  "config":"三角関数で端点座標。中央に大きな数値テキスト",
  "analysis":"現在値がどのゾーン（危険/注意/良好）にあるか瞬時に判断。",
  "use":"スコア表示。例：「データ品質スコアのゲージ」",
  "datatable":{"headers":["指標名","達成率(%)"],"rows":[["完全性",92],["正確性",85],["一貫性",78]]}
},
63: {
  "title":"市場シェア ワッフルチャート",
  "flow":("指標名×割合(%)","100セルのグリッドに変換","ワッフルチャート"),
  "tips":["1セル=1%なので直感的にパーセンテージを体感できる"],
  "warn":["複数カテゴリの場合は色の区別を明確に"],
  "lib":"HTML/CSS","ctype":"waffle (10×10 grid)",
  "code":"// CSS Grid で 10×10\n.waffle {\n  display: grid;\n  grid-template-columns:\n    repeat(10, 1fr);\n}\n// i < pct のセルを着色",
  "config":"10×10 グリッド。i < pct で着色、それ以外はグレー",
  "analysis":"着色セル数から割合を直感的に把握。100%に対する位置を体感。",
  "use":"割合の直感表現。例：「市場シェアのワッフル表示」",
  "datatable":{"headers":["指標名","割合(%)"],"rows":[["食品",38],["家電",42],["日用品",20]]}
},
64: {
  "title":"パフォーマンススコア スピードメーター",
  "flow":("指標名×スコア値","角度に変換→針を配置","スピードメーター"),
  "tips":["赤/橙/緑の3ゾーンで健全性を直感的に伝える"],
  "warn":["針の角度計算を正確に（min/maxの範囲をマッピング）"],
  "lib":"SVG","ctype":"speedometer (needle gauge)",
  "code":"// SVG で3色半円弧 + 針\n<path d={greenArc} fill='#059669'/>\n<path d={orangeArc} fill='#D97706'/>\n<path d={redArc} fill='#DC2626'/>\n<line ... /> <!-- 針 -->",
  "config":"3色の半円弧。値を角度に変換し needle を配置",
  "analysis":"針の位置からスコアのゾーン（良好/注意/危険）を瞬時に判断。",
  "use":"ステータス表示。例：「投資パフォーマンス・スコア」",
  "datatable":{"headers":["指標名","スコア"],"rows":[["ROI",78],["成長率",85],["リスク管理",68]]}
},
65: {
  "title":"商品一覧 データテーブル",
  "flow":("構造化データ（多列）","テーブルHTML生成","データテーブル"),
  "tips":["ソート・フィルター機能を加えるとインタラクティブに"],
  "warn":["列数が多すぎると横スクロールが必要になる"],
  "lib":"HTML/CSS","ctype":"table",
  "code":"<table>\n  <thead><tr>\n    <th>商品名</th><th>カテゴリ</th>\n    <th>単価</th>\n  </tr></thead>\n  <tbody>...</tbody>\n</table>",
  "config":"border-collapse。tr:hover で行ハイライト",
  "analysis":"詳細データの確認とソートによるランキング把握。",
  "use":"詳細データ一覧。例：「商品一覧テーブル」",
  "datatable":{"headers":["商品名","カテゴリ/単価/在庫数/ステータス"],"rows":[["商品A","食品 / ¥950 / 45 / 販売中"],["商品B","家電 / ¥7,500 / 32 / 新商品"],["商品C","衣料 / ¥5,500 / 28 / 入荷待ち"]]}
},
66: {
  "title":"部門別 月次推移スパークバー",
  "flow":("カテゴリ×時系列値","各行にミニ棒を配置","スパークバー"),
  "tips":["テーブル内に埋め込んでトレンドを補助表示"],
  "warn":["棒が小さすぎると差が見えない。高さを十分に確保する"],
  "lib":"HTML/CSS","ctype":"inline bars (mini)",
  "code":"// div を flex で横並び\n.spark-bar {\n  display: flex;\n  align-items: flex-end;\n  gap: 1px;\n}\n.bar { width: 4px; }",
  "config":"各棒の height を最大値で正規化。最新値をテキストで併記",
  "analysis":"テーブルの数値にトレンドの視覚的コンテキストを追加。",
  "use":"テーブル内トレンド。例：「カテゴリ別の月次推移（ミニ棒）」",
  "datatable":{"headers":["カテゴリ名","時系列値"],"rows":[["食品","28 32 35 38 42"],["家電","18 20 22 24 26"]]}
},
67: {
  "title":"部門別KPI＋トレンド ミニチャート付き",
  "flow":("カテゴリ×数値×時系列","テーブル＋ミニ折れ線","ミニチャート付テーブル"),
  "tips":["変化率（▲/▼）を色付きで表示すると一目でわかる"],
  "warn":["ミニチャートの縦軸は行ごとに異なる場合があるので注意"],
  "lib":"SVG + HTML","ctype":"table + sparkline",
  "code":"// CSS Grid でテーブル的レイアウト\n// 各行に SVG polyline\n<svg viewBox='0 0 80 30'>\n  <polyline points='...' />\n</svg>",
  "config":"CSS Grid + SVG polyline。変化量を ▲/▼ + 色で表示",
  "analysis":"数値の現在値とトレンドを同時に一覧比較。",
  "use":"トレンド付き一覧。例：「カテゴリ別KPI＋推移グラフ」",
  "datatable":{"headers":["カテゴリ名","件数","トレンド"],"rows":[["食品",148,"▲ +15"],["家電",102,"▼ -8"],["日用品",78,"▲ +6"]]}
},
68: {
  "title":"月別売上推移＋主要イベント注釈",
  "flow":("時系列×数値×注目ポイント","折れ線＋アノテーション","アノテーション付チャート"),
  "tips":["注目ポイントは2〜3箇所に絞る。多すぎると騒がしくなる"],
  "warn":["アノテーションのテキストが長すぎるとチャートが見にくくなる"],
  "lib":"Chart.js","ctype":"line + annotation",
  "code":"// pointRadius を配列で特定点のみ大きく\npointRadius: data.map(\n  (v,i) => highlights.includes(i)\n    ? 6 : 0\n)",
  "config":"特定点の pointRadius/pointBackgroundColor を変更。吹き出し追加も可",
  "analysis":"全体トレンドの中で特筆すべきイベントや異常値を強調。",
  "use":"イベント付き推移。例：「売上推移＋主要イベント」",
  "datatable":{"headers":["月","売上高","注目ポイント"],"rows":[["1月",120,"通常"],["2月",155,"新商品発売"],["3月",188,"通常"]]}
},
69: {
  "title":"部門別 月次推移スモールマルチプル",
  "flow":("カテゴリ別×時系列データ","同一チャートを小さく複製","スモールマルチプル"),
  "tips":["全パネルのY軸を統一すると比較しやすい"],
  "warn":["パネル数が多すぎると個別の読み取りが困難"],
  "lib":"Chart.js","ctype":"small multiples (grid of charts)",
  "code":"// CSS Grid で複数 canvas を配置\nsectors.forEach(s => {\n  new Chart(\n    document.getElementById(`sm-${s.id}`),\n    { type:'line', data:s.data }\n  );\n});",
  "config":"CSS Grid で 4列。各 canvas に独立した Chart。Y軸統一推奨",
  "analysis":"カテゴリ間のパターン（成長/停滞/周期性）の違いを一覧比較。",
  "use":"カテゴリ間比較。例：「カテゴリ別の月次推移を並べて比較」",
  "datatable":{"headers":["カテゴリ名","時系列値"],"rows":[["食品","28,32,35,38,42"],["家電","18,20,22,24,26"],["日用品","15,17,19,21,23"]]}
},
70: {
  "title":"業界キーワード ワードクラウド",
  "flow":("テキスト×出現頻度","フォントサイズに変換","ワードクラウド"),
  "tips":["主要キーワードが大きく表示されるのでトレンド把握に有効"],
  "warn":["配置がランダムなので正確な比較には不向き"],
  "lib":"HTML/CSS","ctype":"word cloud (flex-wrap)",
  "code":"// flex-wrap で折り返し配置\n.word {\n  font-size: calc(\n    freq / maxFreq * 36 + 10\n  )px;\n}",
  "config":"font-size を頻度に比例。色をランダムまたはカテゴリ別",
  "analysis":"大きなキーワードが頻出テーマ。全体の語彙傾向を俯瞰。",
  "use":"テキスト分析。例：「業界キーワードの可視化」",
  "datatable":{"headers":["キーワード","出現頻度"],"rows":[["製品",145],["サービス",98],["顧客",76]]}
},
71: {
  "title":"四半期 売上高（棒）＋受注件数（折れ線）",
  "flow":("時系列×2指標（棒＋折れ線）","2つのチャートタイプを重畳","複合チャート"),
  "tips":["棒＝量、折れ線＝率（%）の組み合わせが定番"],
  "warn":["左右Y軸の色を凡例と統一して混乱を防ぐ"],
  "lib":"Chart.js","ctype":"bar + line (combo)",
  "code":"datasets: [\n  { type:'bar', data:amounts,\n    yAxisID:'y' },\n  { type:'line', data:counts,\n    yAxisID:'y1' }\n]",
  "config":"棒 + type:'line' を同時定義。yAxisID で左右分離。order で描画順制御",
  "analysis":"量（棒）と率（折れ線）の連動・乖離パターンを同時把握。",
  "use":"量と率の同時表示。例：「売上高（棒）＋受注件数（折れ線）」",
  "datatable":{"headers":["四半期","売上高","受注件数"],"rows":[["Q1",120,45],["Q2",155,52],["Q3",188,61]]}
},
72: {
  "title":"業績概要 パネル",
  "flow":("複数KPI×値×変化率","パネルカードとして配置","ダッシュボードパネル"),
  "tips":["3〜6パネルに絞って情報過多を避ける"],
  "warn":["パネル間で単位やスケールが異なる場合は明示する"],
  "lib":"HTML/CSS","ctype":"panel (dashboard)",
  "code":"// CSS Grid で 3列パネル\n.panel-grid {\n  display: grid;\n  grid-template-columns:\n    repeat(3, 1fr);\n  gap: 12px;\n}",
  "config":"border + border-radius でカード枠。中央揃えで数値を大きく表示",
  "analysis":"主要KPIの状態を一覧で把握。変化率から好転/悪化を判断。",
  "use":"サマリービュー。例：「投資パフォーマンスの概要パネル」",
  "datatable":{"headers":["指標名","値","変化率"],"rows":[["売上高","150億","+12%"],["顧客数",2450,"+18%"],["利益率","15.5%","+2.3%"]]}
},
73: {
  "title":"今期 vs 前期 KPI比較ダッシュボード",
  "flow":("今期×前期の指標群","左右に並べて比較","比較ダッシュボード"),
  "tips":["同じ指標を横に並べることで差分が明確になる"],
  "warn":["指標数が多すぎると比較が散漫になる"],
  "lib":"HTML/CSS","ctype":"comparison (side-by-side)",
  "code":"// CSS Grid で 2列カード\n.compare {\n  display: grid;\n  grid-template-columns: 1fr 1fr;\n}\n// 各カード内に key-value 一覧",
  "config":"今期は鮮やかな色、前期はグレーで区別",
  "analysis":"同一指標の今期vs前期を横並びで直接比較。差分に注目。",
  "use":"期間比較。例：「今期vs前期のKPI比較ダッシュボード」",
  "datatable":{"headers":["指標名","今期の値","前期の値"],"rows":[["売上高","150億","134億"],["顧客数",2450,2180],["利益率","15.5%","14.2%"]]}
},
74: {
  "title":"業績指数トレンド インジケーター",
  "flow":("時系列×指数値","エリア付き折れ線","トレンドインジケーター"),
  "tips":["pointRadius:0 でクリーンな表現にする"],
  "warn":["短期ノイズに惑わされないよう移動平均も検討"],
  "lib":"Chart.js","ctype":"line (trend area)",
  "code":"datasets: [{\n  data: indexValues,\n  fill: true,\n  pointRadius: 0,\n  borderWidth: 2,\n  backgroundColor:\n    'rgba(37,99,235,.1)'\n}]",
  "config":"fill:true + 低透明度背景。pointRadius:0 でクリーン",
  "analysis":"エリアの傾きと面積からトレンドの方向と勢いを直感的に把握。",
  "use":"トレンド表示。例：「投資指数の推移インジケーター」",
  "datatable":{"headers":["月","指数値"],"rows":[["1月",100],["2月",105],["3月",112]]}
},
75: {
  "title":"自社 vs 業界平均 多軸ベンチマーク",
  "flow":("評価軸×自社×業界平均","グループ棒で横並び比較","ベンチマーク比較"),
  "tips":["自社を色付き、業界平均をグレーにして差別化する"],
  "warn":["業界平均の算出方法（中央値/平均値）を注記する"],
  "lib":"Chart.js","ctype":"bar (grouped benchmark)",
  "code":"datasets: [\n  { label:'自社', data:own,\n    backgroundColor:'#2563EB' },\n  { label:'業界平均', data:avg,\n    backgroundColor:'#E5E9F0' }\n]",
  "config":"2つの datasets。自社=色付き、業界平均=グレー",
  "analysis":"各評価軸で自社が業界平均を上回る/下回るかを比較。",
  "use":"ベンチマーク。例：「自社vs業界平均の多軸比較」",
  "datatable":{"headers":["評価軸","自社スコア","業界平均"],"rows":[["成長性",82,75],["収益性",68,72],["品質",88,80]]}
},
76: {
  "title":"商品別 年次成長モーション",
  "flow":("年次×カテゴリ×指標","バブル散布 + 時間軸アニメ","モーションチャート"),
  "tips":["再生ボタンで時間変化を自動再生できる","バブルサイズで第3軸（規模など）を表現"],
  "warn":["データ点が多すぎると視認性が低下","アニメーション速度はユーザーが認識できる程度に"],
  "lib":"SVG + JavaScript","ctype":"bubble scatter (animated)",
  "code":"// 年次ごとにデータ配列を用意\nconst years = [2018,...,2024];\nconst allData = years.map(y =>\n  items.map(i => ({x, y, r})));\n// setInterval で frame を進めて render()",
  "config":"再生間隔: 1200ms。バブルサイズ r でスケール表現。SVG viewBox で座標管理",
  "analysis":"時間経過に伴うカテゴリ別の位置・規模変化を動的に把握。",
  "use":"時系列変化のアニメーション。例：「商品カテゴリの年次推移」「国別指標の経年変化」",
  "datatable":{"headers":["年","カテゴリ","X指標","Y指標","規模"],"rows":[[2020,"食品",45,52,12],[2020,"家電",60,38,8],[2021,"食品",48,55,14],[2021,"家電",63,41,10]]}
},
77: {
  "title":"リアルタイム アクセス数モニター",
  "flow":("ストリームデータ（定期取得）","ローリング折れ線グラフ","リアルタイムストリームチャート"),
  "tips":["直近N件のウィンドウで表示するとトレンドが見やすい","更新頻度は2〜5秒が適切"],
  "warn":["更新間隔が短すぎるとCPU負荷が高くなる","長時間表示ではメモリリークに注意"],
  "lib":"Chart.js","ctype":"line (auto-updating)",
  "code":"setInterval(() => {\n  chart.data.labels.push(newLabel);\n  chart.data.datasets[0].data.push(v);\n  if (labels.length > maxPts) {\n    labels.shift(); data.shift();\n  }\n  chart.update();\n}, 2000);",
  "config":"maxPoints: 12。更新間隔: 2000ms。animation.duration: 600ms",
  "analysis":"リアルタイムデータの変動をライブで監視。即座に異常検知が可能。",
  "use":"即時更新表示。例：「サーバーアクセス数のリアルタイム監視」「センサーデータのライブモニタリング」",
  "datatable":{"headers":["時刻","値"],"rows":[["10:01",33],["10:02",28],["10:03",35],["10:04",42]]}
},
78: {
  "title":"顧客セグメント別 売上比較",
  "flow":("セグメント名×数値","色分け棒グラフ","セグメント比較"),
  "tips":["降順ソートでランキング感を出す"],
  "warn":["色数が多すぎると識別困難。10色以内に"],
  "lib":"Chart.js","ctype":"bar (color-coded)",
  "code":"datasets: [{\n  data: values,\n  backgroundColor:\n    MC.slice(0, N),\n  borderRadius: 4\n}]",
  "config":"backgroundColor を配列で各棒に異なる色。降順ソート推奨",
  "analysis":"各セグメントの規模差を色付き棒で直接比較。",
  "use":"セグメント別比較。例：「顧客セグメント別の売上」",
  "datatable":{"headers":["顧客セグメント","売上"],"rows":[["セグメントA",580],["セグメントB",380],["セグメントC",220]]}
},
79: {
  "title":"プロジェクト サマリーダッシュボード",
  "flow":("KPI群＋進捗データ","KPIカード＋進捗バーを統合","サマリーダッシュボード"),
  "tips":["全体概要として最初に表示するのが効果的"],
  "warn":["情報を詰め込みすぎない。重要KPIに絞る"],
  "lib":"HTML/CSS","ctype":"composite (cards + bars)",
  "code":"// 上段: KPIカード (CSS Grid)\n// 下段: 進捗バー (CSS Grid)\n.summary {\n  display: flex;\n  flex-direction: column;\n  gap: 12px;\n}",
  "config":"上段 Grid 4列（KPIカード）+ 下段 Grid 3列（進捗バー）",
  "analysis":"プロジェクト全体の健全性を1画面で俯瞰。",
  "use":"ダッシュボード全体。例：「プロジェクト全体の概要」",
  "datatable":{"headers":["指標名","現在値","進捗率(%)"],"rows":[["売上高",2450,85],["顧客数",1850,92],["プロジェクト完了",945,78]]}
},
}

if __name__ == '__main__':
    # Validate all 79 exist
    missing = [i for i in range(1,80) if i not in EXT]
    if missing:
        print(f"Missing: {missing}")
    else:
        print(f"All 79 extended guides defined. Keys: {list(EXT[1].keys())}")
